// Builds the single-file app: inlines blend-parser.js and sample-blend.js into
// index.html so the viewer ships as one .html file (three.js and the zstd
// decoder still load from the jsDelivr CDN).
//
//   node tools/build.mjs                        -> index.html (standalone page)
//   node tools/build.mjs --fragment <out.html>  -> body-only fragment for hosts that
//                                                  supply their own <html>/<head> wrapper
//   add --share-url <https://...> to either       -> public link offered when an in-app
//                                                  browser blocks the file picker
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (f) => fs.readFileSync(path.join(root, 'src', f), 'utf8');
const fragment = process.argv.includes('--fragment');

// Wrap the parser in a function scope so its helpers cannot collide with the page's names.
const parser = read('blend-parser.js').replace(/^export /gm, '');
const parserInline = `const { parseBlend } = (() => {\n${parser}\nreturn { parseBlend };\n})();`;
const sampleInline = read('sample-blend.js').replace(/^export /gm, '');

let html = read('app.html');
const swap = (from, to) => {
  if (!html.includes(from)) throw new Error(`build: marker not found: ${from}`);
  html = html.replace(from, () => to);
};
swap("import { parseBlend } from './blend-parser.js';", parserInline);
swap("import { SAMPLE_NAME, SAMPLE_BASE64 } from './sample-blend.js';", sampleInline);

// --share-url <url>: the page's public link, offered when an in-app browser blocks the file picker.
const shareIdx = process.argv.indexOf('--share-url');
if (shareIdx > 0) {
  const shareUrl = process.argv[shareIdx + 1];
  if (!/^https:\/\/[^\s'"]+$/.test(shareUrl || '')) throw new Error('build: --share-url needs an https URL');
  swap("const SHARE_URL = '';", `const SHARE_URL = '${shareUrl}';`);
}

if (!fragment) {
  html = `<!doctype html>\n<!-- Generated by tools/build.mjs from src/. Edit the files in src/, then rebuild. -->\n<html lang="en">\n<head>\n<meta charset="utf-8">\n` +
    `<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n` +
    `${html}`.replace('<div class="app">', '</head>\n<body>\n<div class="app">') + '\n</body>\n</html>\n';
  // The artifact host pads :root by the safe-area insets; do the same standalone.
  html = html.replace('html, body { height: 100%; }',
    'html, body { height: 100%; }\n  :root { padding-top: env(safe-area-inset-top, 0px); box-sizing: border-box; }');
}
const out = fragment ? path.resolve(process.argv[process.argv.indexOf('--fragment') + 1]) : path.join(root, 'index.html');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, html);
console.log(`wrote ${out} (${(html.length / 1024).toFixed(0)} KB)`);
